### ISSUE TITLE
Is the provided facade colmap database valid? 

### ISSUE THREAD

**Issue by akshay-krishnan** [zhangganlin/GlobalSfMpy#12]
I get the following error when I run `python read_colmap_database.py --dataset_path ../datasets/facade/` 

```
GlobalSfMpy/scripts/read_colmap_database.py", line 70, in <module>
sqlite3.OperationalError: no such table: two_view_geometries
```

Is the provided database valid? Am I missing something?

**Comment by zhangganlin** [comment]
Hi, 
For the facade scene, you need to use Colmap to extract the features and also matches the features first, which are not done by the provided facade database (I just put the folder structure in the repo but not upload the actual colmap database since it is quite big).
The feature extraction and matching are very straight forward using colmap (they have a gui so just some clicks to generate the database).
Let me know if any further questions
