### ISSUE TITLE
Obtained very low-quality ETH3D results using GlobalSfmPy codebase, cannot reproduce paper results

### ISSUE THREAD

**Issue by sfm-user-1** [zhangganlin/GlobalSfMpy#13]
I ran COLMAP on two ETH3D datasets, and then fed the results to GlobalSfmpy. The AUC is reported as quite good (85%+) on ETH3D in Table 3 of the GlobalSfmPy CVPR '23 [paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Zhang_Revisiting_Rotation_Averaging_Uncertainties_and_Robust_Losses_CVPR_2023_paper.pdf):
<img width="460" alt="Screenshot 2024-03-21 at 11 52 44 AM" src="https://github.com/zhangganlin/GlobalSfMpy/assets/141111364/ac83d9a9-e5f5-47a7-a4cf-645fd795a4d2">

I find that the pipeline seems to produce poor-quality results on ETH3D, however:

Terrace
<img width="796" alt="Screenshot 2024-03-21 at 11 33 25 AM" src="https://github.com/zhangganlin/GlobalSfMpy/assets/141111364/db13de01-f792-4261-a050-6bf6406ec83e">

Facade
<img width="626" alt="Screenshot 2024-03-21 at 11 36 32 AM" src="https://github.com/zhangganlin/GlobalSfMpy/assets/141111364/c19c73a3-ece1-4fd5-a74a-04190e5452ab">

Can the authors confirm that this is the expected result?

For reference, the ground truth for [ETH3D Terrace](https://www.eth3d.net/datasets) resembles
<img width="626" alt="Screenshot 2024-03-21 at 11 57 52 AM" src="https://github.com/zhangganlin/GlobalSfMpy/assets/141111364/868e69a0-44d8-4ed2-9abc-4cb4540cf527">

**Comment by zhangganlin** [comment]
Hi,
I just rerun these two scenes, and the results are as below,
terrace
![Screenshot from 2024-03-21 18-23-28](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/5c4ec5b1-9747-4004-8061-a87b40a7fc9b)
facade
![Screenshot from 2024-03-21 18-24-17](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/5a00724f-a433-42b0-95c1-e51ef8e9a39d)

And I found a bug which call the function with wrong type in the python script to extract covariance https://github.com/zhangganlin/GlobalSfMpy/blob/545cfa5d7dbb40a0902ac4e85bbe67884906d33e/scripts/get_covariance_from_colmap.py#L29
But I guess you already noticed that and this is probably not the reason of the poor quality results.
Anyway it is already fixed now. 

Another thing needs to mension is that, when extract feature in colmap, select "PINHOLE" as camera model (which is not the default option in colmap), this is quite important since when transfer the colmap database to ours, I directly use the format of PINHOLE camera model https://github.com/zhangganlin/GlobalSfMpy/blob/545cfa5d7dbb40a0902ac4e85bbe67884906d33e/scripts/read_colmap_database.py#L117

Baiscally the results in ETH3D should not differ much from colmap at least visually.

**Comment by sfm-user-1** [comment]
I see, thanks for checking on this @zhangganlin . One confusion I had was that the instructions on your readme do not indicate anything about this non-default PINHOLE setting though. Can you add the COLMAP script you use to get the results? Could you also update the README instructions?

I highly recommend checking what camera model is used in the `read_colmap_database.py`, instead of assuming the user is using PINHOLE. Could you make that change to the source code?

**Comment by zhangganlin** [comment]
Hi, I agree that I should probably add those instructions in the README to make everything clearer. I will try to add the related script when I have time. This may take some time since I also need to get familiar with this project again as two years has passed.
Here I also provide a easier way if you want to get it work now (This is also the way how I run the experiments). Just use the GUI of colmap, click `Processing->Feature extraction`, and change the camera model to 'PINHOLE', then click `extract`, after extraction finishing, run `Processing->Feature matching`. Then run `Reconstruction -> start reconstruction`. Once it finishes, `File -> Export model as text` would generate the text version of the data that GlobalSfMpy needs.
![Screenshot from 2024-03-26 17-56-05](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/0f723796-9272-4ad5-b595-ef64457071c2)

**Comment by zhangganlin** [comment]
bash script for colmap is uploaded, readme is also updated

**Comment by sfm-user-1** [comment]
Thank you, I am able to get reasonable quality results now with these updates.
